Repository freeCodeCamp/guide, pull requests merged in 2018-03, with the labels that each got.

#3980 Added information regarding Euler's Number
  src/pages/mathematics/e-eulers-number/index.md
Labels: content, discussing

#3788 Update index.md
  src/pages/sql/sql-where-clause/index.md
Labels: content, on ci checks

#3804 Added initial intro to bash page
  src/pages/bash/index.md
Labels: content, on ci checks

#3805 Initial description of JIT compilation
  src/pages/computer-science/just-in-time-compilation/index.md
Labels: content, on ci checks

#3807 Simplified Hello World
  src/pages/python/index.md
Labels: content, on ci checks

#8108 Update react-freecodecamp-search
  package.json
  src/LayoutComponents/search/SearchBar.jsx
  src/LayoutComponents/search/redux/index.js
  src/css/main.scss
  src/layouts/Layout.jsx
  src/pageComponents/search/NoResults.jsx
  src/pageComponents/search/Results.jsx
  src/pageComponents/search/ResultsSkeleton.jsx
  src/pages/search.jsx
  src/redux/reducers.js
  yarn.lock
Labels: blocked, platform

#3834 Add ":wq" as suggested way to exit vim
  src/pages/vim/useful-commands/index.md
Labels: content

#8104 Reformat Markdown for REST API document
  src/pages/rest-api/index.md
Labels: content

#8025 Writing an Article for the Margin Property in CSS
  src/pages/css/properties/margin-property/index.md
Labels: content

#4308 Added article on CSS-Animations
  src/pages/css/using-css-animations/index.md
Labels: content
