Repository freeCodeCamp/guide, pull requests merged in 2018-08, with the labels that each got.

#4114 Args explained
  src/pages/python/args-variable/index.md
Labels: changes requested

#4178 Create Conditional_operator.md
  src/pages/cplusplus/Conditional_operator.md
Labels: changes requested

#8342 Added my changes
  src/pages/javascript/tutorials/how-to-create-popups/index.md
Labels: content

#8336 Create Stubs for Certificate Subfolders
  src/pages/certifications/apis-and-microservices/apis-and-microservices-projects/index.md
  src/pages/certifications/apis-and-microservices/basic-node-and-express/index.md
  src/pages/certifications/apis-and-microservices/index.md
  src/pages/certifications/apis-and-microservices/managing-packages-with-npm/index.md
  src/pages/certifications/apis-and-microservices/mongodb-and-mongoose/index.md
  src/pages/certifications/coding-interview-prep/algorithms/index.md
  src/pages/certifications/coding-interview-prep/data-structures/index.md
  src/pages/certifications/coding-interview-prep/index.md
  src/pages/certifications/coding-interview-prep/project-euler/index.md
  src/pages/certifications/coding-interview-prep/rosetta-code/index.md
  src/pages/certifications/coding-interview-prep/take-home-projects/index.md
  src/pages/certifications/data-visualization/data-visualization-projects/index.md
  src/pages/certifications/data-visualization/data-visualization-with-d3/index.md
  src/pages/certifications/data-visualization/index.md
  src/pages/certifications/data-visualization/json-apis-and-ajax/index.md
  src/pages/certifications/front-end-libraries/bootstrap/index.md
  src/pages/certifications/front-end-libraries/front-end-libraries-projects/index.md
  src/pages/certifications/front-end-libraries/index.md
  src/pages/certifications/front-end-libraries/jquery/index.md
  src/pages/certifications/front-end-libraries/react-and-redux/index.md
  src/pages/certifications/front-end-libraries/react/index.md
  src/pages/certifications/front-end-libraries/redux/index.md
  src/pages/certifications/front-end-libraries/sass/index.md
  src/pages/certifications/information-security-and-quality-assurance/advanced-node-and-express/index.md
  src/pages/certifications/information-security-and-quality-assurance/index.md
  src/pages/certifications/information-security-and-quality-assurance/information-security-and-quality-assurance-projects/index.md
  src/pages/certifications/information-security-and-quality-assurance/information-security-with-helmetjs/index.md
  src/pages/certifications/information-security-and-quality-assurance/quality-assurance-and-testing-with-chai/index.md
  src/pages/certifications/javascript-algorithms-and-data-structures/basic-algorithm-scripting/index.md
  src/pages/certifications/javascript-algorithms-and-data-structures/basic-data-structures/index.md
  src/pages/certifications/javascript-algorithms-and-data-structures/basic-javascript/index.md
  src/pages/certifications/javascript-algorithms-and-data-structures/debugging/index.md
  src/pages/certifications/javascript-algorithms-and-data-structures/es6/index.md
  src/pages/certifications/javascript-algorithms-and-data-structures/functional-programming/index.md
  src/pages/certifications/javascript-algorithms-and-data-structures/index.md
  src/pages/certifications/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/index.md
  src/pages/certifications/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/index.md
  src/pages/certifications/javascript-algorithms-and-data-structures/object-oriented-programming/index.md
  src/pages/certifications/javascript-algorithms-and-data-structures/regular-expressions/index.md
  src/pages/certifications/responsive-web-design/applied-accessibility/index.md
  src/pages/certifications/responsive-web-design/applied-visual-design/index.md
  src/pages/certifications/responsive-web-design/basic-css/index.md
  src/pages/certifications/responsive-web-design/basic-html-and-html5/index.md
  src/pages/certifications/responsive-web-design/css-flexbox/index.md
  src/pages/certifications/responsive-web-design/css-grid/index.md
  src/pages/certifications/responsive-web-design/index.md
  src/pages/certifications/responsive-web-design/responsive-web-design-principles/index.md
  src/pages/certifications/responsive-web-design/responsive-web-design-projects/index.md
Labels: content

#8335 variable static info file changed
  src/pages/cplusplus/tokens-variables/static variable info/index.md
Labels: content

#4130 Wrote short description and demo of factory pattern
  src/pages/software-engineering/design-patterns/factory/index.md
Labels: changes requested, stale

#8368 Delete duplicate aws folder and stub
  src/pages/aws/index.md
Labels: content

#8363 Fixed explanation to make the concept clearer
  src/pages/java/abstract-class/index.md
Labels: changes requested

#8372 Explained theorem
  src/pages/mathematics/pythagorean-theorem/index.md
Labels: content

#8376 feat(guide): Create folder for code documentation guidelines #8375
  src/pages/documentation/index.md
Labels: content

#4462 Added stub for perceptron under neural-networks
  src/pages/machine-learning/neural-networks/convolutional-neural-networks/index.md
  src/pages/machine-learning/neural-networks/generative-adversarial-networks/index.md
  src/pages/machine-learning/neural-networks/multi-layer-perceptron/index.md
  src/pages/machine-learning/neural-networks/perceptron/index.md
  src/pages/machine-learning/neural-networks/recurrent-neural-networks/index.md
Labels: content

#8386 Gradual CSS Linear Gradient additional help
  src/pages/certifications/responsive-web-design/applied-visual-design/create-a-gradual-css-linear-gradient/index.md
Labels: changes requested

#8379 Update index.md
  src/pages/certifications/responsive-web-design/basic-html-and-html5/add-a-submit-button-to-a-form/index.md
Labels: changes requested

#8415 Create index.md
  src/pages/csharp/interface/index.md
Labels: changes requested

#8428 Add Comments in JSX
  src/pages/certifications/front-end-libraries/react/add-comments-in-jsx/index.md
Labels: changes requested

#8126 Changed grooming to refinement in line with official Scrum Guide 3.0
  src/pages/agile/backlog-emergence-and-grooming/index.md
Labels: changes requested

#8040 Write article about Fractions in Maths
  src/pages/mathematics/fractions/index.md
Labels: changes requested, content

#8229 React Nesting Components: First version for hint
  src/pages/certifications/front-end-libraries/react/use-react-to-render-nested-components/index.md
Labels: changes requested

#4539 Added definition, examples, and resource links
  src/pages/html/symbols/index.md
Labels: content
