Repository freeCodeCamp/guide, pull requests merged in 2018-06, with the labels that each got.

#8179 Adding Angular article: Directives
  src/pages/angular/directives/index.md
Labels: content

#5002 Minuscule changes to the Guide
  src/pages/computer-science/shortest-path-on-a-graph/index.md
Labels: changes requested

#8186 Adding Angular article: Views
  src/pages/angular/views/index.md
Labels: content

#8190 Adding Angular article: Lifecycle Hooks
  src/pages/angular/lifecycle-hooks/index.md
Labels: content

#4845 JS collection
  src/pages/javascript/additional-javascript-resources/index.md
Labels: changes requested

#5531 Added Content
  src/pages/mathematics/converting-directly-from-binary-to-hexadecimal/index.md
Labels: changes requested

#4094 Update index.md
  src/pages/typography/where-to-get-fonts/index.md
Labels: changes requested, stale

#8194 Adding Angular article: NgModules
  src/pages/angular/ngmodules/index.md
Labels: content

#8195 Adding Angular article: Animations
  src/pages/angular/animations/index.md
Labels: content

#8193 Adding Angular article: Reactive Extensions
  src/pages/angular/reactive-extensions/index.md
Labels: content

#4048 media queries first version
  src/pages/css/css3-media-queries/index.md
Labels: changes requested, stale

#5490 Math library
  src/pages/c/math/index.md
Labels: changes requested

#7697 Update index.md
  src/pages/computer-hardware/hard-drives/index.md
Labels: content

#4095 Correct the fixed-top code example
  src/pages/bootstrap/navigation-bar/index.md
Labels: changes requested, stale

#4173 Added article for redirect from an HTML Page
  src/pages/html/tutorials/redirect-from-an-html-page/index.md
Labels: changes requested, stale

#4191 Create accessibility-examples.md
  src/pages/accessibility/accessibility-examples/index.md
Labels: changes requested, stale

#6090 Add article for Math Floor
  src/pages/javascript/standard-objects/math/math-floor/index.md
Labels: changes requested

#4354 added simple info about php and databases
  src/pages/php/working-with-databases/index.md
Labels: changes requested

#4379 Reformat C++ overview code samples
  src/pages/cplusplus/index.md
Labels: changes requested

#7047 Math: 3x3 determinant
  src/pages/mathematics/3-by-3-determinants/index.md
Labels: changes requested

#8116 Fix to Scrollbar for Content
  src/css/main.scss
Labels: UX/UI

#8119 Responsiveness Fix with a Navbar toggle button
  src/LayoutComponents/nav/NavItem.jsx
  src/LayoutComponents/nav/NavPanel.jsx
  src/LayoutComponents/nav/SideNav.jsx
  src/css/main.scss
  src/layouts/index.js
Labels: UX/UI, platform

#8202 fix/logo-to-home-page
  src/layouts/index.js
Labels: platform

#8012 C++ : Inline Function Explained
  src/pages/cplusplus/Inline Function/index.md
Labels: content

#6558 Removed the typo ".pdf)" from line 13
  src/pages/java/resources/index.md
Labels: changes requested, stale

#8017 Improve C# article (transfer from #3511)
  src/pages/csharp/index.md
Labels: changes requested, content, merge conflict

#5440 added brutal and post-punk
  src/pages/visual-design/index.md
Labels: changes requested, content

#6087 HTML: Added multiple new tags stubs, and unified naming
  src/pages/html/elements/address-tag/index.md
  src/pages/html/elements/area-tag/index.md
  src/pages/html/elements/article-tag/index.md
  src/pages/html/elements/aside-tag/index.md
  src/pages/html/elements/audio-tag/index.md
  src/pages/html/elements/base-tag/index.md
  src/pages/html/elements/blockquote-tag/index.md
  src/pages/html/elements/body-tag/index.md
  src/pages/html/elements/canvas-tag/index.md
  src/pages/html/elements/doctype-tag/index.md
  src/pages/html/elements/head-tag/index.md
  src/pages/html/elements/input-tag/index.md
  src/pages/html/elements/input/index.md
  src/pages/html/elements/nav-tag/index.md
  src/pages/html/elements/nav/index.md
  src/pages/html/elements/section-tag/index.md
  src/pages/html/elements/strong-tag/index.md
Labels: changes requested

#6561 Minor text fixes
  src/pages/logic/truth-tables/index.md
Labels: changes requested, stale

#4563 Enhanced the box shadow guide
  src/pages/css/box-shadow/index.md
Labels: changes requested, stale

#4411 First pass with links
  src/pages/agile/self-organization/index.md
Labels: changes requested, stale

#4112 Added char example
  src/pages/java/variables/index.md
Labels: changes requested, on ci checks, stale

#8027 Added a section about use cases for lambda expressions.
  src/pages/python/lambda-expressions/index.md
Labels: content, discussing

#4184 Erase–remove idiom
  src/pages/cplusplus/erase-remove/index.md
Labels: blocked, changes requested, stale

#8141 Use proper em dashes in README
  README.md
Labels: bikeshedding, enhancement

#4393 Fixed formatting and typos
  src/pages/java/strings/index.md
Labels: changes requested, stale

#4417 fix typos, correct name of node_modules dir
  src/pages/developer-tools/npm/index.md
Labels: changes requested, stale

#5143 Update index.md to address some typos and awkward phrasings
  src/pages/python/what-is-python-used-for/index.md
Labels: changes requested, stale

#5015 Fix typos and grammar
  src/pages/jquery/jquery-click-method/index.md
Labels: changes requested, stale

#4711 Fixed a few typos.
  src/pages/python/what-is-python-used-for/index.md
Labels: changes requested, stale

#5625 JavaScript in Miscellaneous: update index.md to correct some typos and fix broken hyperlinks
  src/pages/miscellaneous/capitalize-the-first-letter-of-a-string/index.md
Labels: changes requested, stale

#8211 Remove incorrect information
  src/pages/cplusplus/compilers/index.md
Labels: content, fix

#8101 Added changes to Embarrassingly Parallel Algo
  src/pages/algorithms/embarassingly-parallel-algorithms/index.md
Labels: changes requested

#8047 Add content to "Convert Fractions to Percents"
  src/pages/mathematics/convert-fractions-to-percents/index.md
Labels: content

#8213 Content added to File System module in Node.js article
  src/pages/nodejs/file-system/index.md
Labels: changes requested, content

#8214 remove errant rocket links
  src/pages/certifications/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/arguments-optional/index.md
Labels: fix

#4149 Create Dataset Splitting Page
  src/pages/machine-learning/dataset-splitting/index.md
Labels: changes requested, content

#4808 Edit to align with style guide
  src/pages/working-in-tech/imposter-syndrome/index.md
Labels: changes requested, stale

#4248 Add information about User-Centered Design
  src/pages/user-experience-design/user-centered-design/index.md
Labels: changes requested, stale

#6118 Add the text "Web accessibility should also include the people who d…
  src/pages/accessibility/index.md
Labels: changes requested, stale

#4545 added new file
  src/pages/working-in-tech/open-source/open-source-newbie/index.md
Labels: changes requested

#7105 add css/properties/flex-basis article with image examples
  src/pages/css/layout/flexbox/flex-basis-property/index.md
Labels: changes requested

#4333 grammar fixes
  src/pages/cplusplus/terms-to-know-for-beginners/index.md
Labels: changes requested, stale
