Repository freeCodeCamp/guide, pull requests merged in 2018-10, with the labels that each got.

#8775 XML: Introduction to XML
  src/pages/xml/index.md
Labels: content

#8762 rename illegally formatted folder name
  src/pages/css/current-color-keyword/index.md
Labels: content

#8874 D3: Data Driven Documents
  src/pages/d3/index.md
  src/pages/mathematics/conditional-probability/index.md
Labels: content

#8940 Removed duplicated lines in cpp code example.
  src/pages/cplusplus/index.md
Labels: content

#9141 Applied Accessibility
  src/pages/certifications/responsive-web-design/applied-accessibility/avoid-colorblindness-issues-by-carefully-choosing-colors-that-convey-information/index.md
Labels: content

#9145 Applied Accessibility
  src/pages/certifications/responsive-web-design/applied-accessibility/make-links-navigatable-with-html-access-keys/index.md
Labels: content

#8907 ionic helloworld tutorial
  src/pages/ionic/hello-world-in-ionic/index.md
Labels: blocked, changes requested

#9255 Updated the state file to include more information about State with e…
  src/pages/react/state/index.md
Labels: on ci checks

#9272 Fix hyperlink on python web dev page
  src/pages/python/using-python-for-web-development/index.md
Labels: content

#9337 Update index.md
  src/pages/html/lists/index.md
Labels: content

#8715 Added instructions
  src/pages/certifications/front-end-libraries/react/create-a-component-with-composition/index.md
  src/pages/certifications/responsive-web-design/css-grid/create-your-first-css-grid/index.md
Labels: content

#5172 Added universal selector guide
  src/pages/css/selectors/general/universal/index.md
Labels: content

#5184 Added description for storyboards
  src/pages/user-experience-research/storyboards/index.md
Labels: content

#5196 adding time box duration for a sprint planning
  src/pages/agile/sprint-planning/index.md
Labels: content

#5208 Added multiple box shadows
  src/pages/css/box-shadow/index.md
Labels: content

#9348 Highskillzz patch 2
  src/pages/redux/redux-thunk/index.md
Labels: content

#9378 Solution.md
  src/pages/certifications/javascript-algorithms-and-data-structures/basic-javascript/use-the-conditional-ternary-operator/index.md
Labels: blocked, changes requested

#9566 Adds CSS Flebox Challenge guides
  src/pages/certifications/responsive-web-design/css-flexbox/add-flex-superpowers-to-the-tweet-embed/index.md
  src/pages/certifications/responsive-web-design/css-flexbox/align-elements-using-the-justify-content-property/index.md
  src/pages/certifications/responsive-web-design/css-flexbox/apply-the-flex-direction-property-to-create-a-column-in-the-tweet-embed/index.md
  src/pages/certifications/responsive-web-design/css-flexbox/apply-the-flex-direction-property-to-create-rows-in-the-tweet-embed/index.md
  src/pages/certifications/responsive-web-design/css-flexbox/use-display-flex-to-position-two-boxes/index.md
  src/pages/certifications/responsive-web-design/css-flexbox/use-the-flex-direction-property-to-make-a-column/index.md
  src/pages/certifications/responsive-web-design/css-flexbox/use-the-flex-direction-property-to-make-a-row/index.md
  src/pages/javascript/template-literals.md
Labels: content

#9396 Add Javascript Web Speech API information
  src/pages/voice/index.md
Labels: changes requested

#5096 Explained with more detail and correctly
  src/pages/cplusplus/input-and-output/index.md
Labels: merge conflict

#5122 Add content for Threads
  src/pages/computer-science/threads/index.md
Labels: merge conflict

#5223 Updated illustrator description
  src/pages/designer-tools/illustrator/index.md
Labels: merge conflict

#9738 Updates to the guide
  src/pages/bootstrap/get-started/index.md
  src/pages/bootstrap/index.md
  src/pages/certifications/responsive-web-design/css-flexbox/index.md
  src/pages/certifications/responsive-web-design/css-grid/index.md
Labels: content

#8800 Add: Nodejs Process Object
  src/pages/nodejs/process/index.md
Labels: content

#9828 Fix typo
  src/pages/computer-science/databases/key-value-databases/index.md
Labels: content

#9829 Fix typo
  src/pages/computer-science/compilers/index.md
Labels: content

#9831 **Devops: Fixed a typo**
  src/pages/devops/index.md
Labels: content

#9833 Fix grammar
  src/pages/computer-science/databases/indexes/index.md
Labels: content

#9835 Fix grammar
  src/pages/blockchain/index.md
Labels: content

#9808 MAINT: fixing typoes on Accessibility main page
  src/pages/accessibility/index.md
Labels: content

#9889 Create EigenFaces.md
  src/pages/machine-learning/principal-component-analysis/eigen-faces/index.md
Labels: content

#9915 fixes #9888 - jQuery Event Method article is about Bootstrap grid
  src/pages/jquery/jquery-event-method/index.md
Labels: content

#9916 Renamed C# substring directory
  src/pages/csharp/substring/index.md
Labels: content

#9949 VirtualBox: add Install on macOS guide
  src/pages/virtualbox/install-virtualbox-on-macos/index.md
Labels: content

#9912 Create OOPs Basics.md
  src/pages/design-patterns/OOPs Basics.md
Labels: content

#9967 Fix: Created a new directory and renamed file to fix Travis build.
  src/pages/design-patterns/index.md
  src/pages/design-patterns/object-oriented-programming/index.md
Labels: content

#8904 Algorithms: add Boundary_fill
  src/pages/algorithms/boundary-fill/index.md
Labels: content

#9126 Added the udacity nanodegree program coursework
  src/pages/android-development/index.md
Labels: content

#9330 CSS: Import a Google Font .md
  src/pages/certifications/responsive-web-design/basic-css/import-a-google-font/index.md
Labels: content

#9316 update typo cplusplus main page
  src/pages/cplusplus/index.md
Labels: content

#9240 Configure and set up D3
  src/pages/d3/set-up-d3/index.md
Labels: content

#9932 Create Radio Button.md
  src/pages/html/tutorials/basic-html/radio-button/index.md
Labels: content

#9570 typo fix in Dunning Kruger effect
  src/pages/working-in-tech/dunning-kruger-effect/index.md
Labels: changes requested

#9318 Added "why tensorflow", "what is a tensor" sections in the article
  src/pages/data-science-tools/tensor-flow/index.md
Labels: changes requested

#10026 Fix: Broken Netlify Build Due to Unscaped Character in `src/pages/css/index.md`
  src/pages/css/index.md
Labels: content

#10063 Typo
  src/pages/algorithms/search-algorithms/binary-search/index.md
Labels: invalid

#9981 Blockchain: Added more Resources and done some styling.
  src/pages/blockchain/index.md
Labels: content

#10158 Fixes #10094
  src/pages/certifications/front-end-libraries/react/access-props-using-this-props/index.md
Labels: content

#5109 Update index.md
  src/pages/security/scanning/index.md
Labels: merge conflict

#5594 update to index.md
  src/pages/computer-hardware/ram/index.md
Labels: merge conflict

#5116 Article on Clustering Algorithms
  src/pages/machine-learning/clustering-algorithms/index.md
Labels: merge conflict

#5047 Updated semi-colons for javasctipt
  src/pages/javascript/semicolons/index.md
Labels: merge conflict

#5136 Adding null-coalescing operator
  src/pages/csharp/null-coalescing-operator/index.md
Labels: merge conflict

#9825 Added information about Chef
  src/pages/chef/index.md
Labels: changes requested

#5227 Add additional commands and streamline article
  src/pages/vim/useful-commands/index.md
Labels: merge conflict

#5302 Accessibility: added additional contexts and editing punctuation
  src/pages/accessibility/accessibility-basics/index.md
Labels: changes requested

#10265 Fixes #10259
  src/pages/certifications/front-end-libraries/react/set-state-with-this-setstate/index.md
  src/pages/certifications/front-end-libraries/react/use-array-filter-to-dynamically-filter-an-array/index.md
  src/pages/certifications/front-end-libraries/react/use-array-map-to-dynamically-render-elements/index.md
Labels: content

#10263 React: Use Array.map() Hints and Solution
  src/pages/certifications/front-end-libraries/react/use-array-map-to-dynamically-render-elements/index.md
Labels: content

#10270 React: Use Array.filter hints and solution
  src/pages/certifications/front-end-libraries/react/use-array-filter-to-dynamically-filter-an-array/index.md
Labels: content

#10281 fix Markdown syntax for [Readme_portuguese.md]
  translations/Readme_portuguese.md
Labels: content

#8738 Added solution
  src/pages/certifications/front-end-libraries/react/create-a-stateless-functional-component/index.md
Labels: content

#8737 Added solution
  src/pages/certifications/front-end-libraries/react/learn-about-self-closing-jsx-tags/index.md
Labels: content

#5586 Added link to C# article
  src/pages/game-development/unity/index.md
Labels: merge conflict

#5583 py2 vs py3
  src/pages/python/python-2-vs-python-3/index.md
Labels: merge conflict

#5575 stringexample
  src/pages/java/strings/index.md
Labels: merge conflict

#5455 added information about clustering algorithm
  src/pages/machine-learning/clustering-algorithms/index.md
Labels: changes requested

#8951 Added link to great article by Dan Abramov
  src/pages/redux/index.md
Labels: blocked, changes requested

#5598 Added the video
  src/pages/html/responsive-web-design/index.md
Labels: merge conflict

#8841 Book: Hacking
  src/pages/book-recommendations/index.md
Labels: changes requested

#5577 add text about relative and absolute units
  src/pages/css/units/index.md
Labels: merge conflict

#8797 Add: Nodejs EventEmitter
  src/pages/nodejs/event-emitters/index.md
Labels: content

#8796 Add the text "Where, b1, b2 are the lengths of each base h is the al…
  src/pages/mathematics/area-of-trapezoids/index.md
Labels: changes requested

#8793 Add: Streams in Nodejs
  src/pages/nodejs/streams/index.md
Labels: content

#8791 Add: Buffer API in Nodejs
  src/pages/nodejs/buffer/index.md
Labels: content

#8789 Add the text "Types of Motherboards. Motherboards come in different s…
  src/pages/computer-hardware/motherboard/index.md
Labels: changes requested

#8786 fix: spacing between the content paragraphs
  src/pages/nodejs/index.md
Labels: enhancement

#8714 Change Information about React Native CLI
  src/pages/algorithms/algorithm-design-patterns/behavioral-patterns/index.md
  src/pages/mathematics/decimals-fractions-and-percentages/index.md
  src/pages/react-native/basic-commands/index.md
Labels: enhancement

#8900 Added solution to Create Your First CSS Grid
  src/pages/certifications/responsive-web-design/css-grid/create-your-first-css-grid/index.md
Labels: content

#8849 Added solution to Pass Props to a Stateless Functional Component
  src/pages/certifications/front-end-libraries/react/pass-props-to-a-stateless-functional-component/index.md
Labels: content

#8846 Solution to Compose React Components
  src/pages/certifications/front-end-libraries/react/compose-react-components/index.md
Labels: content

#5296 Create Array Destructuring Guide
  src/pages/javascript/standard-objects/array/array-destructuring/index.md
Labels: changes requested

#5343 Vectors: create introduction to vectors article
  src/pages/mathematics/vectors/introduction-to-vectors/index.md
Labels: changes requested

#8774 Fix: Meaning of DPI
  src/pages/react-native/screen-dimensions/index.md
Labels: fix

#8773 Fix and Add information
  src/pages/react-native/functional-vs-class-components/index.md
Labels: content, enhancement, fix
