Repository freeCodeCamp/guide, pull requests merged in 2018-02, with the labels that each got.

#8038 Add syntax highlighting to Ruby Array Methods example
  src/pages/ruby/common_array_methods/index.md
Labels: content, fix

#8039 Improve reference to Ruby Arrays in Ruby Arrays Methods
  src/pages/ruby/common_array_methods/index.md
Labels: content

#3648 Added content regarding Gaussian process
  src/pages/machine-learning/gaussian-process/index.md
Labels: content, on ci checks

#3642 Added 2 additional types
  src/pages/machine-learning/index.md
Labels: content, on ci checks

#6970 Added a benefit of using a foreach loop
  src/pages/csharp/foreach/index.md
Labels: content

#3654 Update to Sketch description index.md
  src/pages/designer-tools/sketch/index.md
Labels: content

#3634 Update Ansible documentation
  src/pages/devops/ansible/index.md
Labels: content, on ci checks

#3638 Update index.md
  src/pages/javascript/booleans/index.md
Labels: content, on ci checks

#7641 Started the article
  src/pages/agile/functional-managers/index.md
Labels: content

#3641 added new category
  src/pages/working-in-tech/women-in-tech/index.md
Labels: content, on ci checks

#3626 Added definition and wikipedia article
  src/pages/user-experience-design/human-computer-interaction/index.md
Labels: content, on ci checks

#8058 remove left over stub text in xaml article
  src/pages/csharp/xaml/index.md
Labels: content, on ci checks

#3640 Description of Personas with an informative link
  src/pages/user-experience-design/personas/index.md
Labels: content, on ci checks

#3679 Added a definition
  src/pages/mathematics/fibonacci-sequence/index.md
Labels: content, on ci checks

#3682 Stub updated
  src/pages/mathematics/area-of-a-sector/index.md
Labels: content, on ci checks

#3643 Update index.md
  src/pages/react/index.md
Labels: content, merge conflict

#3644 Add my changes
  src/pages/bootstrap/bootstrap-icons/index.md
Labels: content

#3650 Update Assembly Language
  src/pages/computer-science/assembly-language/index.md
Labels: content, on ci checks

#3657 Updated Other Resources link
  src/pages/html/elements/ul-tag/index.md
Labels: content

#3659 Added Other Resources link
  src/pages/html/elements/ol-tag/index.md
Labels: content

#3645 Updated Actual Time Estimation
  src/pages/agile/actual-time-estimation/index.md
Labels: content, on ci checks

#3646 Added Information regarding Monte Carlo
  src/pages/machine-learning/monte-carlo/index.md
Labels: content, on ci checks

#8080 Added elixir data types article
  src/pages/elixir/data-types/index.md
Labels: content

#8083 Create Elixir Stubs
  src/pages/elixir/behaviours/index.md
  src/pages/elixir/comprehensions/index.md
  src/pages/elixir/concurrency/index.md
  src/pages/elixir/control-structures/index.md
  src/pages/elixir/custom-mix-tasks/index.md
  src/pages/elixir/debugging/index.md
  src/pages/elixir/documentation/index.md
  src/pages/elixir/ecto/index.md
  src/pages/elixir/embedded-elixir/index.md
  src/pages/elixir/enumerables/index.md
  src/pages/elixir/erlang-interoperability/index.md
  src/pages/elixir/erlang-term-storage/index.md
  src/pages/elixir/error-handling/index.md
  src/pages/elixir/executables/index.md
  src/pages/elixir/functions/index.md
  src/pages/elixir/genstage/index.md
  src/pages/elixir/iex-helpers/index.md
  src/pages/elixir/iex/index.md
  src/pages/elixir/keyword-lists/index.md
  src/pages/elixir/lists/index.md
  src/pages/elixir/maps/index.md
  src/pages/elixir/meta-programming/index.md
  src/pages/elixir/mix/index.md
  src/pages/elixir/mnesia/index.md
  src/pages/elixir/modules/index.md
  src/pages/elixir/operations/index.md
  src/pages/elixir/otp-concurrency/index.md
  src/pages/elixir/otp-supervisors/index.md
  src/pages/elixir/pattern-matching/index.md
  src/pages/elixir/pipe-operator/index.md
  src/pages/elixir/plug/index.md
  src/pages/elixir/protocols/index.md
  src/pages/elixir/sigils/index.md
  src/pages/elixir/specifications-and-types/index.md
  src/pages/elixir/strings/index.md
  src/pages/elixir/testing/index.md
  src/pages/elixir/tuples/index.md
  src/pages/elixir/umbrella-projects/index.md
Labels: content

#3700 Added info on adding a custom cursor image
  src/pages/css/css-cursors/index.md
Labels: content

#3701 Added introduction info
  src/pages/machine-learning/bayes-classifier/index.md
Labels: content

#8042 fix #8028 broken breadcrumbs
  src/pageComponents/search/Results.jsx
Labels: platform

#3688 Added :focus pseudo-class article
  src/pages/css/selectors/pseudo/focus/index.md
Labels: content

#3677 Update index.md
  src/pages/html/lists/index.md
Labels: content

#3692 Added :link pseudo-class article
  src/pages/css/selectors/pseudo/link/index.md
Labels: content, on ci checks

#3705 Added "Layouts organize different areas of the web page"
  src/pages/html/layouts/index.md
Labels: content, on ci checks

#3680 Add HTML Element Article
  src/pages/html/elements/article/index.md
Labels: content, merge conflict

#3710 Changes
  src/pages/html/semantic-html-elements/index.md
Labels: content, on ci checks

#3687 added text and link in the what to learn more
  src/pages/python/index.md
Labels: content, merge conflict

#3721 Added info on parameter passing and code example
  src/pages/java/methods/index.md
Labels: content

#3717 update grammar, revise
  src/pages/html/html5-audio/index.md
Labels: content, merge conflict, on ci checks

#3716 Added Truth tables for or, not, imply.
  src/pages/logic/truth-tables/index.md
Labels: content, on ci checks

#3685 Add "Extended Functionality" to article
  src/pages/javascript/advantages-and-disadvantages-of-javascript/index.md
Labels: content, merge conflict

#3745 Update index.md
  src/pages/python/learn-about-python-sets/index.md
Labels: content, on ci checks

#8018 Renamed more certificate to match challenge names. Moved Algorithm Pe…
  src/pages/algorithms/algorithm-performance/index.md
  src/pages/certificates/compound-assignment-with-augmented-addition/index.md
  src/pages/certificates/compound-assignment-with-augmented-division/index.md
  src/pages/certificates/compound-assignment-with-augmented-multiplication/index.md
  src/pages/certificates/compound-assignment-with-augmented-subtraction/index.md
  src/pages/certificates/extend-constructors-to-receive-arguments/index.md
  src/pages/certificates/find-more-than-the-first-match/index.md
  src/pages/certificates/match-all-numbers/index.md
  src/pages/certificates/match-whitespace/index.md
  src/pages/certificates/pre-filter-json-to-get-the-data-you-need/index.md
  src/pages/certificates/repeat-a-string-repeat-a-string/index.md
  src/pages/certificates/telephone-number-validator/index.md
  src/pages/certificates/use-closure-to-protect-properties-within-an-object-from-being-modified-externally/index.md
  src/pages/certificates/use-the-filter-method-to-extract-data-from-an-array/index.md
  src/pages/certificates/use-the-map-method-to-extract-data-from-an-array/index.md
Labels: content

#8033 Fix More Info section in Common Ruby Arrays Methods article
  src/pages/ruby/common_array_methods/index.md
Labels: content

#3691 Update index.md
  src/pages/php/index.md
Labels: content, on ci checks

#3762 revise second half, simplify code examples
  src/pages/jquery/jquery-click-method/index.md
Labels: content, on ci checks

#3738 revise, clarify grammar
  src/pages/jquery/jquery-click-method/index.md
Labels: content, on ci checks

#8089 add examples, clarify language
  src/pages/html/responsive-web-design/index.md
Labels: content

#3749 Added more information links for HTML5 Video
  src/pages/html/html5-video/index.md
Labels: content, on ci checks

#3750 Added initial text to guide about the li tag
  src/pages/html/elements/li-tag/index.md
Labels: content, on ci checks

#3748 Add method, examples and converter from Google.
  src/pages/mathematics/converting-units-centimeters-to-meters/index.md
Labels: content, on ci checks
