Repository freeCodeCamp/guide, pull requests merged in 2018-09, with the labels that each got.

#8337 Added some explanation and the answer
  src/pages/certifications/javascript-algorithms-and-data-structures/es6/create-strings-using-template-literals/index.md
Labels: changes requested

#4165 Add Ruby Hash in ruby folder
  src/pages/ruby/ruby-hash/index.md
Labels: content

#4270 Updated index.md with check # of factors
  src/pages/mathematics/all-factors-of-a-number/index.md
Labels: changes requested

#4153 Add Vagrant description
  src/pages/developer-tools/vagrant/index.md
Labels: changes requested, stale

#4293 Update index.md
  src/pages/html/tutorials/images-in-html/index.md
Labels: changes requested, content, stale

#4295 Added introduction
  src/pages/mathematics/linear-algebra/spans/index.md
Labels: changes requested

#4390 Update index.md
  src/pages/vim/index.md
Labels: changes requested

#4480 Brief Intro
  src/pages/agile/actual-time-estimation/index.md
Labels: changes requested

#4482 Brief Intro
  src/pages/agile/design-patterns/index.md
Labels: changes requested

#4483 Update index.md
  src/pages/logic/logical-operators/index.md
Labels: changes requested

#4532 Add basics about Flexbox
  src/pages/css/layout/flexbox/index.md
Labels: changes requested

#4541 PullReq for new article <img>-tag
  src/pages/html/tutorials/images-in-html/index.md
Labels: changes requested, content

#6023 Clarify ordered and unordered lists definitions
  src/pages/html/lists/index.md
Labels: changes requested, stale

#4498 Added sources to article on Unconscious Bias
  src/pages/working-in-tech/unconscious-bias/index.md
Labels: changes requested

#6582 Initial article submission.
  src/pages/javascript/standard-objects/math/math-max/index.md
Labels: changes requested, stale

#4682 Added info about ACs helping fight scope creep
  src/pages/agile/acceptance-criteria/index.md
Labels: changes requested

#4731 Added my changes
  src/pages/security/trojans/index.md
Labels: changes requested

#4774 Update index.md
  src/pages/machine-learning/principal-component-analysis/index.md
Labels: changes requested

#4805 Update index.md
  src/pages/html/tutorials/how-to-use-links/index.md
Labels: content

#4810 Update HTML/index.md
  src/pages/html/index.md
Labels: content

#4814 Created folder for Generics
  src/pages/java/generics/index.md
Labels: content

#4848 Update index.md
  src/pages/algorithms/divide-and-conquer-algorithms/index.md
Labels: content

#8666 Update solution.
  src/pages/certifications/front-end-libraries/sass/nest-css-with-sass/index.md
Labels: content

#8674 Create a stub (index.md) for Gatsby.js
  src/pages/gatsbyjs/index.md
Labels: changes requested, enhancement

#8690 !Important Overrides in CSS.md
  src/pages/certifications/responsive-web-design/basic-css/override-all-other-styles-by-using-important/index.md
Labels: content

#8689 ID Attribution Overrides in CSS.md
  src/pages/certifications/responsive-web-design/basic-css/override-class-declarations-by-styling-id-attributes/index.md
Labels: content

#4887 Added definition of geometry & subtopics
  src/pages/mathematics/geometry/index.md
Labels: content

#4927 Added "Advantage & Disadvantage" section
  src/pages/mobile-app-development/index.md
Labels: content

#4939 Added more information on scopes
  src/pages/javascript/scopes/index.md
Labels: content

#8717 Impostor Syndrome: Fixed error in Famous Women Link
  src/pages/working-in-tech/imposter-syndrome/index.md
Labels: fix
