Repository freeCodeCamp/guide, pull requests merged in 2018-07, with the labels that each got.

#6413 Added info & formatted existing info
  src/pages/bootstrap/form-inputs/index.md
Labels: changes requested, stale

#5639 Update index.md
  src/pages/bootstrap/form-inputs/index.md
Labels: changes requested, stale

#4669 change "large" to "small"
  src/pages/bootstrap/buttons/index.md
Labels: changes requested, stale

#6629 JavaScript: Added Math.pow article
  src/pages/javascript/standard-objects/math/math-pow/index.md
Labels: changes requested, stale

#6619 JavaScript: Added Math.sqrt article
  src/pages/javascript/standard-objects/math/math-sqrt/index.md
Labels: changes requested, stale

#4573 Binary search
  src/pages/algorithms/search-algorithms/binary-search/index.md
  src/pages/algorithms/search-algorithms/linear-search/index.md
Labels: changes requested

#4592 My modifications to Quantum computing
  src/pages/computer-science/quantum-computing/index.md
Labels: changes requested

#7660 Mathematics: Fourier Series
  src/pages/mathematics/fourier-series/index.md
Labels: changes requested

#7602 Update index.md
  src/pages/mathematics/counting/rule-of-sum/index.md
Labels: changes requested

#7485 Add code in C++ with explanation
  src/pages/computer-science/data-structures/linked-lists/index.md
Labels: changes requested

#4255 Added complete guide to finding area of ellipse
  src/pages/mathematics/area-of-a-ellipse/index.md
Labels: changes requested, stale

#4772 Added article for database indexes
  src/pages/computer-science/databases/indexes/index.md
Labels: content

#8234 Update index.md
  src/pages/electron/index.md
Labels: changes requested, content

#8250 Apply Functional Programming to Convert Strings to URL Slugs solution.md
  src/pages/certifications/javascript-algorithms-and-data-structures/functional-programming/apply-functional-programming-to-convert-strings-to-url-slugs/index.md
Labels: changes requested, content

#4706 Reformat C++ if statement sample code
  src/pages/cplusplus/the-if-statement/index.md
Labels: changes requested

#4710 Reformat C++ Input and Output code samples
  src/pages/cplusplus/input_and_output/index.md
Labels: changes requested

#8266 Add es6: prevent object mutation stub
  src/pages/certifications/javascript-algorithms-and-data-structures/es6/prevent-object-mutation/index.md
Labels: content

#8263 Feature/add hints pages for basic JS
  src/pages/certifications/javascript-algorithms-and-data-structures/basic-javascript/add-two-numbers-with-javascript/index.md
  src/pages/certifications/javascript-algorithms-and-data-structures/basic-javascript/build-javascript-objects/index.md
  src/pages/certifications/javascript-algorithms-and-data-structures/basic-javascript/create-decimal-numbers-with-javascript/index.md
  src/pages/certifications/javascript-algorithms-and-data-structures/basic-javascript/declare-javascript-variables/index.md
  src/pages/certifications/javascript-algorithms-and-data-structures/basic-javascript/divide-one-decimal-by-another-with-javascript/index.md
  src/pages/certifications/javascript-algorithms-and-data-structures/basic-javascript/divide-one-number-by-another-with-javascript/index.md
  src/pages/certifications/javascript-algorithms-and-data-structures/basic-javascript/finding-a-remainder-in-javascript/index.md
  src/pages/certifications/javascript-algorithms-and-data-structures/basic-javascript/generate-random-fractions-with-javascript/index.md
  src/pages/certifications/javascript-algorithms-and-data-structures/basic-javascript/multiply-two-numbers-with-javascript/index.md
Labels: content

#4162 Ruby string interpolation document.
  src/pages/ruby/ruby-string-interpolation/index.md
Labels: content

#8284 Added static variable info Issue #4019
  src/pages/cplusplus/tokens-variables/static variable info
Labels: content

#4031 Add a Hello World example for React
  src/pages/react/hello-word.md
Labels: content

#8265 Add es6: mutate an array declared with const stub
  src/pages/certifications/javascript-algorithms-and-data-structures/es6/mutate-an-array-declared-with-const/index.md
Labels: content

#4091 Added content
  src/pages/security/confidentiality-integrity-availability/index.md
Labels: changes requested, content

#3986 Added information about images in html
  src/pages/html/tutorials/images-in-html/index.md
Labels: changes requested, content

#4164 Added Ruby Symbol in ruby folder
  src/pages/ruby/ruby-symbols/index.md
Labels: content

#8294 Removed Errant Links/Typo in markdown
  src/pages/certifications/javascript-algorithms-and-data-structures/basic-javascript/profile-lookup/index.md
  src/pages/certifications/javascript-algorithms-and-data-structures/basic-javascript/stand-in-line/index.md
Labels: fix

#4110 Added introduction of iterators for vectors.
  src/pages/cplusplus/vector/index.md
Labels: changes requested
