Repository freeCodeCamp/guide, pull requests merged in 2018-05, with the labels that each got.

#8060 Added article on "Breadth First Search"
  src/pages/algorithms/graph-algorithms/breadth-first-search/index.md
Labels: content

#8145 Updated localStorage guide
  src/pages/javascript/window-localstorage/index.md
Labels: content

#3886 Added a brief section on quantum computation
  src/pages/computer-science/quantum-computing/index.md
Labels: content

#3916 Update index.md
  src/pages/agile/nonfunctional-requirements/index.md
Labels: changes requested

#3920 Update index.md
  src/pages/agile/backlog-emergence-and-grooming/index.md
Labels: changes requested

#3951 Update index.md
  src/pages/agile/design-patterns/index.md
Labels: changes requested

#8148 Setting up Firebase Realtime Database in Android Studio
  src/pages/android-development/firebase/realtime-database/setup/index.md
Labels: content

#4142 Add more details to "Planning Poker" article
  src/pages/agile/planning-poker/index.md
Labels: changes requested

#4007 Moving external links to the bottom of the article
  src/pages/javascript/loops/continue-statement/index.md
Labels: changes requested

#4045 Created other resources section
  src/pages/javascript/loops/for-of-loop/index.md
Labels: changes requested

#4043 Moved distracting links at the bottom of the article
  src/pages/javascript/loops/for-in-loop/index.md
Labels: changes requested

#8065 Added article on "Degrees to Radians"
  src/pages/mathematics/degrees-to-radians/index.md
Labels: content

#6093 Developer tools: add stubs for dev tools in browsers
  src/pages/developer-tools/developer-tools-in-browsers/chrome-developer-tools/index.md
  src/pages/developer-tools/developer-tools-in-browsers/chrome-developer-tools/javascript-console/index.md
  src/pages/developer-tools/developer-tools-in-browsers/chrome-developer-tools/javascript-debugger/index.md
  src/pages/developer-tools/developer-tools-in-browsers/chrome-developer-tools/network-performance/index.md
  src/pages/developer-tools/developer-tools-in-browsers/chrome-developer-tools/profiling-memory-and-execution/index.md
  src/pages/developer-tools/developer-tools-in-browsers/chrome-developer-tools/render-performance/index.md
  src/pages/developer-tools/developer-tools-in-browsers/firefox-developer-tools/index.md
  src/pages/developer-tools/developer-tools-in-browsers/index.md
  src/pages/developer-tools/developer-tools-in-browsers/internet-explorer-developer-tools/index.md
Labels: changes requested, content

#8153 Fix typo in blockchain index
  src/pages/blockchain/index.md
Labels: fix

#3964 Initial commit Vagrant index
  src/pages/developer-tools/vagrant/index.md
Labels: changes requested

#3907 add Create Table as Select (CTAS) section
  src/pages/sql/sql-create-table/index.md
Labels: changes requested

#8159 Adding Content Expressjs
  src/pages/nodejs/express/index.md
Labels: content

#3922 Updated index.md
  src/pages/python/code-blocks-and-indentation/index.md
Labels: changes requested, content

#5006 Add page about Terraform
  src/pages/devops/terraform/index.md
Labels: content

#4854 "Added article for Tagging in Git "
  src/pages/git/tagging-in-git/index.md
Labels: changes requested

#4266 Various updates to index.md
  src/pages/javascript/falsy-values/index.md
Labels: changes requested

#3996 Added depreciation notes and pointed to css page
  src/pages/html/attributes/body-background-attribute/index.md
Labels: changes requested

#3935 Initial commit
  src/pages/computer-science/hexcode/index.md
  src/pages/computer-science/what-is-an-api/index.md
Labels: changes requested, stale

#3940 Update index.md
  src/pages/javascript/code-linting-in-javascript/index.md
Labels: changes requested, stale

#3987 Pairing Fonts.md
  src/pages/typography/combining-typefaces/index.md
Labels: changes requested, stale

#4000 Added Running time for BST
  src/pages/algorithms/binary-search-trees/index.md
Labels: changes requested, stale

#4066 Update index.md
  src/pages/jquery/index.md
Labels: changes requested, stale

#6119 Git: update git tag article
  src/pages/git/tagging-in-git/index.md
Labels: changes requested, content

#8182 Adding Angular article: Services and Injectors
  src/pages/angular/services-and-injectors/index.md
Labels: content
